### ISSUE TITLE
Fault on y-axis fails

### ISSUE THREAD

**Issue by tbenthompson** [cossatot/tri_dislocations_python#1]
I tried to use the code a bit today and ran into this issue. A fault that lies along the y-axis results in a whole bunch of NaN output. I pasted a minimal example that's based off of test/test.py.

Cheers,
Ben

``` python
import numpy as np
import matplotlib.pyplot as plt
import tde.tde as T


# tri dislocation parameters
pr = 0.25
ss = -1.0
ts = 0.0
ds = 0.0
N = 30

sx, sy, sz = np.meshgrid(np.linspace(0.5, 3, N), np.linspace(0.5, 3, N), 0)
sxr = sx.ravel(order='F')
syr = sy.ravel(order='F')
szr = sz.ravel(order='F')

X = np.array([0.0, 1.0, 0.0])
Y = np.array([0.0, 0.0, 0.0]) # Changing any one of the y coordinates to 0.001 results in no problem.
Z = np.array([0.0, 0.0, 1.0])

S = T.calc_tri_strains(sxr, syr, szr, X, Y, Z, pr, ss, ts, ds)
U = T.calc_tri_displacements(sxr, syr, szr, X, Y, Z, pr, ss, ts, ds)
```

**Comment by cossatot** [comment]
Thanks, Ben.

There was a zero divide error when a parameter (beta) was zero.  I've changed the function that calculates beta to make it epsilon (smallest float value at machine precision) which fixes the zero divide problem.  However, it's not giving me the same results as the Matlab code in this case.  I don't know when I will have a chance to look into it more, but I committed the code before I checked against Matlab...  So it's up there.

**Comment by tbenthompson** [comment]
Cool! I also tried setting one of the y-values to epsilon instead of all zero and that resulted in numerical noise as output. 

The problem is rotationally symmetric about the vertical axis. So, it could make sense to just rotate the triangle off the y-axis and then rotate back after the calculation.

**Comment by cossatot** [comment]
Yeah, I was getting displacements ~1E+14 or whatever, which isn't surprising when the computations involve dividing by epsilon. I just really want to know how Matlab handles this gracefully, or if I've got a bigger bug somewhere else.  It's bugging me so I'm putting off my real work until I fix it.

**Comment by cossatot** [comment]
Ok, I got it.  When beta was near zero, the Matlab code simply set all strains and displacements to zero.  I've matched the code and the answers are the same.

Thanks for finding this bug.  I didn't do much checking of edge cases etc. as I probably should have.

Cosed with commit e8cab67

**Comment by tbenthompson** [comment]
Yay!

**Comment by cossatot** [comment]
Note that I forgot to add the displacement functions corrections until just now.  Too many vim windows panels open...
